"""empty message

Revision ID: 661db56e8c5e
Revises: 
Create Date: 2023-06-16 13:47:29.131843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661db56e8c5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('time', sa.String(length=10), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.Column('details', sa.String(length=255), nullable=False),
    sa.Column('requirements', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meritbadge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('badge_name', sa.String(length=50), nullable=False),
    sa.Column('eagle_required', sa.Boolean(), nullable=True),
    sa.Column('logo', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('badge_name')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.String(length=255), nullable=False),
    sa.Column('profile_pic', sa.String(length=255), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('scout', 'tenderfoot', 'second_class', 'first_class', 'star', 'life', 'eagle', name='rankenum'), nullable=False),
    sa.Column('rank', sa.Enum('leader', 'scout', name='roleenum'), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('positions')
    op.drop_table('meritbadge')
    op.drop_table('meetings')
    # ### end Alembic commands ###
